- README.md
- lib/prompts/base.js
- lib/prompts/rawlist.js
- lib/utils/tty.js
- package.json
and some minor other cleanup
`mute-stream` isn't used anywhere
`cli-color` is moot as you can do the same without
-
Can you push a new release when this is merged?
> get rid of some moot dependencies

- .gitignore
> No need for npm-debug.log file to be commited

- README.md
Small README update.
I tested Inquirer on gnome-terminal and konsole
> Updates the list of supported Linux terminals

- test/specs/inquirer.js
Hey @SBoudrias maybe worth adding a test?
> add test for #326

- lib/utils/events.js
- test/specs/prompts/checkbox.js
- test/specs/prompts/list.js
FYI: the README specifies "wip" as the branch to target for feature adds. I'm guessing that's outdated.
> Add Emacs up/down keybindings

- README.md
It Works too!! (Yes, just adding a simple line on the readme file)
> Add ConEmu to the list.

- README.md
I've recently spent some time on creating a smaller yet powerful [alternative](https://github.com/leo/args) to commander. If you ask me, it's a better way to build CLIs. If you think like that as well, I would be very happy if it could be added to the recommendations... :blush:
Oh. And I've also suggested inquirer in the description of course (when it comes to user input)!
> Recommend args

- examples/hierarchical.js
Hi there,
This is an example of hierarchical flow using inquirer.
e.g. 
```
A - B1 - C1
\
B2 - C2
```
Its kind of trivial since deriving this from other examples is easy, but I was looking for something like that for a second.
> feat(example/hierarchical): Added an example of hierarchical flow

- lib/prompts/checkbox.js
Added simple check to ensure that the checkbox is not undefined in the onSpaceKey method.
> Fixed #423

- examples/rx-observable-array.js
- examples/rx-observable-create.js
Added some examples from RxJS, removed my README comments, as this is relatively unneeded when users see examples. Created a new, cleaner PR, as much was wrong with my repo during previous PR.
Hope you find this well, and thanks for the info during the PR! 
Even
> Examples for RxJS

- package.json
Closes #465
https://greenkeeper.io/
> fix(package): update external-editor to version 2.0.1

- package.json
Closes #482
https://greenkeeper.io/
> fix(package): update cli-cursor to version 2.1.0

- lib/prompts/base.js
- test/specs/api.js
> Fix issue when failing promise-based validation

- lib/ui/bottom-bar.js
Fixes SBoudrias/Inquirer.js#485
I hope I did this correctly new to using Git.
> Fix BottomBar.log.write not working

- lib/prompts/password.js
- test/specs/prompts/password.js
Fixes https://github.com/SBoudrias/Inquirer.js/issues/177
> Password prompt should display no characters

- README.md
Since #254 it has been possible to receive the answers hash via an option's `validate` function.
This PR adds this information to the docs.
Cheers 👍
> Update validate fn param docs

- lib/prompts/base.js
- test/specs/api.js
resolve https://github.com/SBoudrias/Inquirer.js/issues/428 😉
> pass current answers hash to filter

- README.md
I apologize for the large number of commits (I was using GitHub to preview).  Squash and merge please.
> Add Plugins Section to README.md

- README.md
I added new inquirer prompts for selecting index in an array where should be added a new element.
> add inquirer-select-line to plugins

- README.md
-  Add [inquirer-chalk-pipe](https://github.com/LitoMore/inquirer-chalk-pipe) to plugins list
:)
> Add related plugin in readme

- lib/prompts/expand.js
- lib/prompts/list.js
- lib/prompts/rawlist.js
- test/specs/prompts/expand.js
- test/specs/prompts/rawlist.js
- Feel free to drop this PR if it's not a direction you want to move in.
> Adds string default option for list and rawlist

- README.md
- lib/prompts/input.js
- test/specs/prompts/input.js
> Pass answers object to transformer functions

- examples/input.js
- package.json
- yarn.lock
- Add `transformer` example for input
[chalk-pipe](https://github.com/LitoMore/chalk-pipe) is a good use case for `transformer`.
Just try some colors like `orange`, `#ff99cc`..
> Add transformer example

- examples/rx-observable-array.js
- examples/rx-observable-create.js
- lib/prompts/base.js
- lib/prompts/checkbox.js
- lib/prompts/confirm.js
- lib/prompts/editor.js
- lib/prompts/expand.js
- lib/prompts/input.js
- lib/prompts/list.js
- lib/prompts/password.js
- lib/prompts/rawlist.js
- lib/ui/prompt.js
- lib/utils/events.js
- lib/utils/utils.js
- package.json
- test/specs/inquirer.js
Hi again!
This is a follow-up PR from our discussion here: https://github.com/SBoudrias/Inquirer.js/pull/652
I followed rxjs's [MIGRATION.md](https://github.com/ReactiveX/rxjs/blob/0e1f9d6bbd770d01d9b0a45aa652fd8589b61eb7/MIGRATION.md).
Thanks for having such a comprehensive test suite. 🤜 🤛
> rxjs 6 upgrade

- lib/ui/prompt.js
- test/specs/inquirer.js
return that mutated answers array when all when functions return false.
Ref: #517 
Ref: #645
> when set answer value in when and return false ignore prompt, user can get the value last.

- README.md
This adds a link to the examples folder.
> feat: add link to examples folder

- package-lock.json
- packages/inquirer/lib/prompts/checkbox.js
> Only remove checkbox help message after first space keypress

- package-lock.json
- packages/inquirer/lib/prompts/rawlist.js
> Rawlist bug #769 fixed

- README.md
For these lazy people(me included) to save one extra enter
> Add inquirer-autosubmit-prompt

- package-lock.json
- packages/inquirer/lib/prompts/rawlist.js
> Bug #776 fixed

- README.md
A simple plugin for inputting emojis.  Hopefully others could find it useful.
> Add inquirer-emoji to README

- package-lock.json
- package.json
- packages/inquirer/package-lock.json
- packages/inquirer/package.json
Fixes #782 
Upstream: https://github.com/chalk/strip-ansi/pull/26, https://github.com/chalk/ansi-regex/issues/28
> Support terminal link in prompt message

- packages/inquirer/lib/prompts/password.js
- packages/inquirer/test/specs/prompts/password.js
> Clear password field on backspace

- packages/inquirer/lib/prompts/checkbox.js
https://github.com/SBoudrias/Inquirer.js/issues/838
> add spaceKeyPressed

- README.md
Available at https://github.com/eduardoboucas/inquirer-table-prompt.
> Add inquirer-table-prompt plugin

- .project
- README.md
- packages/inquirer/lib/ui/baseUI.js
Fixes https://github.com/SBoudrias/Inquirer.js/issues/899
> Remove windows workaround and add known issues to README.

- .travis.yml
- README.md
- packages/inquirer/lib/inquirer.js
- packages/inquirer/lib/ui/prompt.js
- packages/inquirer/test/specs/inquirer.js
Add a parameter for a pre-filed answers.
Use case:
Allow to easily skip already answered question, but allowing following questions to use the skipped answers.
> Add support to pre-filed answers.

- README.md
added robin-rpr/inquirer-search-list plugin to README.md
> docs: ✏️ add inquirer-search-list to plugin list

- README.md
Adds documentation for filter answers hash support which was added in #533
> add documentation for changes made to add answers hash to filter in #533

- README.md
- packages/inquirer/lib/prompts/list.js
- packages/inquirer/lib/prompts/rawlist.js
- packages/inquirer/lib/utils/incrementListIndex.js
- packages/inquirer/test/specs/prompts/list.js
- packages/inquirer/test/specs/prompts/rawlist.js
> feat: add loop: false for list type prompts

- README.md
Minor PR to add [`inquirer-date-plugin`](https://www.npmjs.com/package/inquirer-date-prompt) package to the README. 🚀
> docs: add updated date plugin

- packages/inquirer/lib/prompts/list.js
- packages/inquirer/test/specs/inquirer.js
- packages/inquirer/test/specs/prompts/list.js
> fix: passes answers to list's filter callback

- README.md
Had a lot of trouble understanding the wording on notes regarding "default" around list, rawlist and expand. Tried my best to make them easy as possible to understand while retaining the original meaning. Also added small tweaks that will hopefully be viewed as formatting improvements
> Notes on defaults improvements

- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/lib/ui/prompt.js
us built in version of isArray instead
> fix: Replace _.isArray with native

- packages/inquirer/lib/objects/choice.js
- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/lib/prompts/expand.js
- packages/inquirer/lib/prompts/list.js
...My goal: totally remove bloated lodash dependency one tiny bit at the time
> fix: Remove dependency of lodash isString

- README.md
This is something that I lost a lot of time on and I saw that I wasn't the only one to deal with this issue. Figured I'd add it to the README to save others some time
> Add grunt-exec known issue to README

- README.md
I created an Inquirer "press to continue" prompt that I thought other people might find helpful!
> Mention `inquirer-press-to-continue` prompt in README

- README.md
Times change. Windows Terminal is the next-generation terminal emulator for Windows developers. They should know this.
Some of our issues on Windows occurred with their old-school terminal emulators.
I will search for some specific cases and link them here.
> Add Windows Terminal to support list

- packages/select/src/index.ts
Set default cursorPosition to the first non-disabled item.
> feat(select): set default cursorPosition to the first non-disabled item

- packages/confirm/README.md
- packages/confirm/demo.mts
- packages/confirm/src/index.mts
Synchronize feature with https://github.com/SBoudrias/Inquirer.js/pull/1212 in the new `confirm` prompt.
> feat(confirm): add transformer feature for the new confirm prompt

- packages/checkbox/README.md
> fix: checkbox readme error

- .github/workflows/main.yml
Related to https://github.com/SBoudrias/Inquirer.js/pull/1245#issuecomment-1575326137
> Codecov: Ignore `*.test.js` files

- packages/inquirer/README.md
> fix (docs): Fixed image url

- packages/inquirer/README.md
A table editing prompt for Inquirer.
[**inquirer-table-input**](https://github.com/edelciomolina/inquirer-table-input)<br>
> New Prompt <> inquirer-table-input

- packages/select/select.test.mts
- packages/select/src/index.mts
Fix #1216
Search feature for `@inquirer/select`. Basing myself on the `<select>` HTML search ergonomics.
> Feat: Support search in the select prompt

- packages/checkbox/src/index.mts
- packages/checkbox/tsconfig.cjs.json
- packages/checkbox/tsconfig.json
- packages/confirm/tsconfig.cjs.json
- packages/confirm/tsconfig.json
- packages/core/tsconfig.cjs.json
- packages/core/tsconfig.json
- packages/editor/tsconfig.cjs.json
- packages/editor/tsconfig.json
- packages/expand/tsconfig.cjs.json
- packages/expand/tsconfig.json
- packages/input/tsconfig.cjs.json
- packages/input/tsconfig.json
- packages/password/tsconfig.cjs.json
- packages/password/tsconfig.json
- packages/prompts/tsconfig.cjs.json
- packages/prompts/tsconfig.json
- packages/rawlist/tsconfig.cjs.json
- packages/rawlist/tsconfig.json
- packages/select/src/index.mts
- packages/select/tsconfig.cjs.json
- packages/select/tsconfig.json
- packages/testing/tsconfig.cjs.json
- packages/testing/tsconfig.json
- packages/type/tsconfig.cjs.json
- packages/type/tsconfig.json
- tools/setup-packages.mjs
We should be able to handle those now that we dropped Node 16.
> Chore: tackle TODO for Array#findLastIndex()

- packages/prompts/README.md
I made an extended version of the select prompt for a project I was working on, and I am happy to share it with others who may find it useful.
> Add inquirer-action-select community prompt to README.md

- .eslintrc.json
> Try to not have to compile app to get eslint to pass

- packages/prompts/README.md
I developed a toggle prompt for a recent project and decided to share it with the community. Feel free to provide feedback or suggestions for improvement.
> Add inquirer-toggle community prompt

- packages/inquirer/lib/objects/choices.js
- packages/inquirer/lib/prompts/checkbox.js
> Feat(inquirer): Make Choices class iterable + add .some() support

- packages/prompts/README.md
https://github.com/jeffwcx/inquirer-select-pro
> Add inquirer-select-pro community prompt

- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/lib/prompts/list.js
- packages/inquirer/lib/utils/screen-manager.js
- packages/inquirer/package.json
- yarn.lock
Leaner package, less esm only deps.
> Chore(inquirer): Drop cli-cursor dependency

- packages/input/input.test.mts
- packages/input/src/index.mts
> Add required option to input prompt

- integration/esm/integration.test.mjs
- packages/inquirer/package.json
- turbo.json
> Fix(inquirer): Fix changed paths from internals used by plugin vendors.

- packages/inquirer/src/ui/prompt.mts
- packages/inquirer/test/inquirer.test.mts
Fixes #1473
Tests passing locally:
> Fixed bug where overriding a boolean value with an object path caused a runtime error

- packages/search/search.test.mts
- packages/search/src/index.mts
Minor DX issue using the search prompt.
> Fix(@inquirer/search) Type the source function to allow default parameters

- packages/number/number.test.mts
- packages/number/src/index.mts
Due to javascript floating point arithmetic the current code does not support decimal numbers as input. However, by multiplying by with 10^6 this now works as intended.
> fix(@inquirer/number): Allowing decimal numbers

- packages/prompts/README.md
https://github.com/br14n-sol/inquirer-file-selector
> Add inquirer-file-selector community prompt

- packages/core/core.test.mts
- packages/core/src/lib/create-prompt.mts
- packages/core/src/lib/screen-manager.mts
Fixes #1497
Related to #1407
Thanks @cAttte for the suggestion!
> Fix(@inquirer/core) Improve rendering performance

- packages/inquirer/src/types.mts
- packages/inquirer/src/ui/prompt.mts
+ Refactor to reduce usage of RX
> Refactor(inquirer): Reduce usage of RX

- packages/core/src/lib/create-prompt.mts
Alternative answer to #1536.
2 challenges this code brings:
1. Calling done from a hook cleanup can easily lead to an infinite loop (this code handles it, and there's a unit test covering this case already.)
2. The cycle function becomes a bit more complex - might need to revisit this piece. Looked into extracting it out in #1543
> Refactor(@inquirer/core): Streamline exit handlers

- .github/workflows/main.yml
- eslint.config.js
- packages/demo/.tshy/build.json
- packages/demo/.tshy/esm.json
- packages/demo/package.json
- packages/demo/src/demos/checkbox.ts
- packages/demo/src/demos/confirm.ts
- packages/demo/src/demos/editor.ts
- packages/demo/src/demos/expand.ts
- packages/demo/src/demos/input.ts
- packages/demo/src/demos/loader.ts
- packages/demo/src/demos/number.ts
- packages/demo/src/demos/password.ts
- packages/demo/src/demos/rawlist.ts
- packages/demo/src/demos/search.ts
- packages/demo/src/demos/select.ts
- packages/demo/src/demos/timeout.ts
- packages/demo/src/index.ts
- packages/demo/tsconfig.json
- tools/setup-packages.mjs
- yarn.lock
Trying to get a end-to-end test with the packages.
Thinking is to rewrite `@inquirer/demo` in Typescript, and extract it in a github action to ensure it works as expected in isolation from the repo setup.
> Extract demo module for testing in isolation from the repo setup

- .github/workflows/main.yml
- packages/demo/package.json
- packages/demo/tsconfig.json
- yarn.lock
Partial extraction from #1569 - and further improvements (ideally don't wanna use npm just for this...)
> Chore(test): Isolate a tsc run

- internals/hoist-peer-dependencies/index.js
- internals/hoist-peer-dependencies/package.json
- package.json
- packages/checkbox/package.json
- packages/confirm/package.json
- packages/demo/package.json
- packages/editor/package.json
- packages/expand/package.json
- packages/input/package.json
- packages/inquirer/package.json
- packages/number/package.json
- packages/password/package.json
- packages/prompts/package.json
- packages/rawlist/package.json
- packages/search/package.json
- packages/select/package.json
- packages/testing/package.json
- tools/setup-packages.mjs
- yarn.lock
> Fix(*): Make sure peerDependencies of deps are hoisted through each package.

- packages/core/core.test.ts
- packages/core/src/lib/theme.ts
- packages/core/src/lib/use-prefix.ts
> feat: Supports custom status types

- packages/confirm/confirm.test.ts
- packages/confirm/src/index.ts
> Feat(confirm): Toggle value on tab keypress.

- packages/inquirer/inquirer.test.ts
- packages/inquirer/src/types.ts
- packages/inquirer/src/ui/prompt.ts
Fixes https://github.com/SBoudrias/Inquirer.js/issues/1626
> inquirer(feat): re-add checkbox prompt support for `default` prop

- package.json
- packages/checkbox/README.md
- packages/confirm/README.md
- packages/core/README.md
- packages/editor/README.md
- packages/expand/README.md
- packages/input/README.md
- packages/inquirer/README.md
- packages/number/README.md
- packages/password/README.md
- packages/prompts/README.md
- packages/rawlist/README.md
- packages/search/README.md
- packages/select/README.md
- packages/testing/README.md
Adding Warp as a project sponsor.
cc @ericdachen had to reopen a PR to edit.
> ♥ Warp sponsorship

- packages/core/core.test.ts
- packages/core/package.json
- packages/core/src/lib/screen-manager.ts
- packages/testing/package.json
- packages/testing/src/index.ts
- yarn.lock
> Chore(*): Replace strip-ansi with node:util stripVTControlCharacters

- packages/checkbox/README.md
- packages/checkbox/checkbox.test.ts
- packages/checkbox/src/index.ts
Address the feature request for customized shortcuts in #1648.
(First time contribute, lmk if there is any suggestion)
> Feat: support customize shortcuts for checkbox selection/deselection

- packages/core/src/lib/key.ts
to follow @inquirer/core Key utilities readme:
isNumberKey() one of 1, 2, 3, 4, 5, 6, 7, 8, 9, 0
> Fix(@inquirer/core): include 0 to isNumberKey

- packages/checkbox/README.md
- packages/confirm/README.md
- packages/core/README.md
- packages/editor/README.md
- packages/expand/README.md
- packages/input/README.md
- packages/number/README.md
- packages/password/README.md
- packages/prompts/README.md
- packages/rawlist/README.md
- packages/search/README.md
- packages/select/README.md
- packages/testing/README.md
> Chore: Graphite started sponsoring Inquirer <3

- packages/select/README.md
- packages/select/select.test.ts
- packages/select/src/index.ts
> Feat(@inquirer/select): Expose customization of the usage instructions

- packages/rawlist/README.md
- packages/rawlist/rawlist.test.ts
- packages/rawlist/src/index.ts
> Feat(@inquirer/rawlist): Support using arrow keys on the rawlist prompt

- packages/prompts/README.md
Adds another prompt to the README: https://github.com/patik/inquirer-select-with-state
Relates to https://github.com/SBoudrias/Inquirer.js/issues/1735
> Add community prompt inquirer-select-with-state

- packages/core/core.test.ts
- packages/core/src/lib/use-state.ts
> Fix(@inquirer/core): Make sure useState set functions are always bound to the async context

- .gitignore
- packages/search/search.test.ts
- packages/search/src/index.ts
> feat(@inquirer/search): Support providing custom instructions
