SBoudrias/Inquirer.js

- lib/prompts/base.js
- lib/utils/tty.js
- package.json
Prevents scripts from crashing if using a `debugger` with `node debug my-script.js` while accepting feedback from user.
> Fix cli width issue for `node debug`, fixes #207

- lib/objects/choices.js
Issue #223
`Separator.prototype.toString` works great when we use `new inquirer.Separator() `, but when we use inquirer.js in Yeoman and try to pass plain object:
```javascript
{
type: "separator",
line: ">>>>>>>>"
}
``` 
we get `[object Object]`
> #223 Separator as a plain object

- lib/prompts/checkbox.js
- test/specs/prompts/checkbox.js
Suppling a truthy value to 'checked' resulted in the list item
being selected visually, but it was missing from the selected
elements list.
'checked' is now coerced to a boolean when selected items are
queried.
This patch closes #242.
> 'checked' improperly handles truthy values

- lib/prompts/base.js
- test/specs/api.js
fix #198 
This was the simplest fix I could see. If you don't like making the answers available on the prompt itself, I'm open to suggestions about how else it could be done.
> make the current answers available within validate fn

- lib/inquirer.js
- lib/ui/baseUI.js
- lib/ui/bottom-bar.js
- lib/ui/prompt.js
- test/helpers/readline.js
Adds a third option to the `inquirer.prompt` method to allow for configurable input/output streams.
When no value is supplied defaults to `process.stdin`/`process.stdout`.
@SBoudrias
> Adds an option to configure input/output streams, fixes #279

- lib/utils/screen-manager.js
In some environment, `cli-width` is known to return a default value of
`0`, which causes inquirer to crash in such a context.
Fixes: https://github.com/SBoudrias/Inquirer.js/issues/290
> Set a default cli width of 80 characters

- lib/prompts/checkbox.js
- lib/prompts/expand.js
- lib/prompts/list.js
- lib/prompts/rawlist.js
- lib/utils/paginator.js
Prompts that use the paginator (checkbox, expand, list, and rawList) can now be passed an optional pageSize parameter. Defaults to 7.
> added pageSize option for prompts that use paginator

- README.md
I noticed you were kind enough to add a plug for Commander in your readme. 
[Vorpal.js](https://github.com/dthree/vorpal) is rapidly gaining traction thanks to awesome [things like this](http://developer.telerik.com/featured/creating-node-js-command-line-utilities-improve-workflow/), and a lot of people are now apparently finding it really useful, from their feedback.
I'm trying to spread the word around and thought it'd be awesome if your page could suggest Vorpal as well as Commander. You can totally say no, but I thought I'd at least suggest it. :smiley: 
As Vorpal both uses Inquirer and is inspired by Commander, I take definite strides to promote both of those projects wherever I can as well.
> Add suggestion for Vorpal.js as a CLI utility

- examples/checkbox.js
- lib/objects/choices.js
- lib/prompts/checkbox.js
- lib/prompts/list.js
Fix bug when a list prompt has separator and is longer than pageSize (using paginator)
The offset of the separator was added to the cursor position but the index of the first line to print was wrong.
> Fix offset separator

- lib/prompts/expand.js
- test/specs/prompts/expand.js
Hey, thanks for your work on this! I interact with it as a user of Ember CLI’s update process.
A surprising number of times, I get the `Please enter a valid command` error because I’ve typed a space before my letter choice. It’s user error and easily remedied by entering the command again without whitespace, but maybe other people make this same mistake and this little tweak would help!
I did see this in the contribution guidelines:
> Send _fixes_ PR on the `master` branch. Any new features should be send on the `wip`branch.
I’m not sure whether this constitutes a bug fix or a new feature, so let me know if I should resubmit to `wip`. Or if there are any other changes I should make.
> Add trimming of choice input

- lib/utils/screen-manager.js
- package.json
I found two bugs when use input prompt.
When prompt message contains multibyte characters (e.g. Chinese/Japanese), the input cursor position will move away:
The reason is result of `width()` function in screen-manager.js doesn't match with display length.
When I moved LEFT key after typed some text in answer area, the cursor does't move; but when I type again, the characters will come out from the front of cursor.
When re-adjust cursor one the right in ScreenManager.render, the column size does't match with real cursor in mute stream
> fix incorrect cursor position

- lib/utils/screen-manager.js
string-width can return a 0 width screen, which causes inquirer to blow up:
https://gist.github.com/bcoe/6bc16d0dbe5190b8d302
I'm submitted a [pull request](https://github.com/knownasilya/cli-width/pull/6) to `cli-width`, but I felt it might be worthwhile to defend against this in inquirer as well.
> add sanity check for screen width

- lib/prompts/expand.js
Choice objects may have a `"short"` property which is defined as a text displayed after selection. However, it doesn't work for all prompt types.
This patch makes `"expand"` work properly with `"short"` properties, that is, prefer it to `"name"` after selection.
> Use "short" property in expanding prompts

- lib/utils/screen-manager.js
- package.json
Greetings my friend @SBoudrias,
**cli-width** finally got a major release with a nicer API to define `defaultWidth` AND the possibility of configure an option **stdout** as described on #285 
This PR updates the dependency to its latest version `v2.0.0` - it's also worth noting that this version also contains a fix to the annoying issue where the default value wouldn't be used, reported and patched on #326
Unfortunately, I had to do a bit of moving around to be able to get the value of `this.rl.output` - please let me know if that's good enough.
Thanks :zap:
> Updates cli-width dependency

- README.md
The description of possible question `type` did not include
* `expand`
* `checkbox`
Add these options (which are present in the `type` detail section).
> Add missing options to question type description

- README.md
After some debugging, found that the `process` attribute is nested under `ui`
> Fix `subscribe` example in README

- lib/ui/baseUI.js
closes #414
- fix issue with custom prompt modules on successive calls
> Ensure provided options aren't overwritten on successive prompt calls

- lib/prompts/base.js
- lib/prompts/list.js
- test/specs/api.js
Changes behavior of errors produced in async filter functions from
throwing to printing the error and reprompting the user for a
non-erroring input. Addresses #363
cc/ @rclark @SBoudrias @iongion
> Add error handling for errors produced in filter function

- lib/prompts/editor.js
The editor result object was properly disposed (which then causes the error message), but the editor stayed subscribed to line events (which causes it to come up again after the next question).  
That subscription is now disposed properly, too, so editor questions can be used again if they are not the last question. So, this fixes issue #442 (editor issues).
> Fix for #442 (editor comes up again if it's not the last question / ObjectDisposedError)

- README.md
- lib/ui/prompt.js
- test/specs/inquirer.js
Consider the following set of questions:
``` js
{
type: 'input',
name: 'name.first',
message: 'What\'s your first name?'
},
{
type: 'input',
name: 'name.last',
message: 'What\'s your last name?'
}
```
The resulting answer object will look something like this:
``` js
{
'name.first': 'John',
'name.last': 'Doe'
}
```
If the `name` properties contains periods, it makes sense that Inquirer
will interpret them as paths in the final answers object, resulting in
something like this instead:
``` js
{
name: {
first: 'John',
last: 'Doe'
}
}
```
This change is implemented by making use of `_.set` when assigning the
value to the answers hash.
Signed-off-by: Juan Cruz Viotti jviotti@openmailbox.org
> Add support for object paths in question names

- lib/prompts/base.js
- package.json
- test/specs/inquirer.js
Since promises are native in `node >= 0.12`.
> Drop `pinkie-promise`.

- lib/ui/prompt.js
It was still being used in `prompt.js`.  Closes #487.  Sorry about that.
> Remove leftover `pinkie-promise`.

- lib/utils/paginator.js
This fixes a somewhat broken implementation of pageSize. It always fixed the list at position 4. So any pageSize below that caused the currently selected item to be out of the visible area.
Now we fix it to the middle of the list.
> Scroller fixed to middle of list

- lib/prompts/base.js
- lib/ui/baseUI.js
- lib/ui/prompt.js
- lib/utils/screen-manager.js
I made some quick changes that implements it the alternative way.
And then I do in my prompt:
```js
Prompt.prototype.close = function() {
if (this.screen.extraLinesUnderPrompt > 0) {
utils.down(this.rl, this.screen.extraLinesUnderPrompt);
}
}
```
This approach makes way less changes to the code. I am in favor of this.
Should also document this behaviour maybe? Nice for prompt authors to know about.
> Clears screen at bottom of prompt - alternative

- lib/ui/baseUI.js
After the changes you @SBoudrias  introduced here https://github.com/SBoudrias/Inquirer.js/commit/79eebac61d2b1843df77435ca938fe3283ff8f5a and that are in 3.0.2, the clearing of the screen does not work any more.
I located what change caused it. This should restore it. Tested with my autocomplete prompt https://github.com/mokkabonna/inquirer-autocomplete-prompt
> Restores functionality of clearing screen

- lib/ui/baseUI.js
- lib/utils/paginator.js
Now if you have a list of pageSize +2 items they are all shown without pagination. IMO it should be strictly fixed pagesize.
Is there any other reason for the +2? Also should the "9" here https://github.com/SBoudrias/Inquirer.js/pull/509/files#diff-232d5c801450a865eb599f3512b9d8c0L27
actually be pageSize +2? I can't see any change when changing the 9.
Issue originally reported here: https://github.com/mokkabonna/inquirer-autocomplete-prompt/issues/23
> Prevent extra items in list, higher than pageSize

- lib/prompts/checkbox.js
The usage hints will not be displyed after these events:
* Default choices are selected
* Using the "a" shortcut to select all items.
* Using the "i" shortcut to inverse current selection. 
Addresses #507
> Checkbox: Do not show usage hints after selection  

- lib/ui/baseUI.js
Can you test this @SBoudrias ? This restores the correct functionality without giving an extra line for me, same for you?
Before you had an console.log('\n') there, but gives an extra line.
> Fix for not clearing final line

- examples/rx-observable-array.js
- examples/rx-observable-create.js
- lib/prompts/editor.js
- lib/ui/prompt.js
- lib/utils/events.js
- lib/utils/utils.js
- package.json
- test/specs/inquirer.js
- yarn.lock
While profiling our dependencies we noticed that inquirer includes the full `rx` module which adds around `7MB` to the inquirer dependencies, vs `~500K` for `rx-lite-aggregates` + `rx-lite`.  One thing I was not entirely happy with was that this bumps `rx` back from `^4.1.0` to `^4.0.8`, which is the latest `rx-lite-aggregates` version.  I also added an `rx-lite` dependency because otherwise `3.1.2` satisfies the `*` version from `rx-lite-aggregates`.
I did see in a8b2ce91fa88dd1c2aeec97c3cf9c220f032acd2 that the `rx-lite` dependency was swapped out for `rx` which I presume was because the `reduce` functionality was needed looking at the diff.  Are there any other reasons why it was changed to `rx`?
```
-> % du -h -s node_modules/rx-lite-aggregates
104K	node_modules/rx-lite-aggregates
-> …
```
> Use rx-lite-aggregates instead of full rx

- lib/ui/baseUI.js
This PR properly addresses https://github.com/SBoudrias/Inquirer.js/issues/293 by triggering a `process.exit(0)` on `SIGINT` on the readline.
> [fix] #293 Exit script when SIGINT signal received

- lib/prompts/list.js
At the moment the list default value only allows Numbers (choice array index) and Strings (choice array values). However, values might as well be anything, not just Strings. (In my case entire database objects with their name as then name of the choice)
This PR allows for any type of default option to be used.
> Allow non-string values as a list default option

- lib/ui/baseUI.js
As per https://github.com/SBoudrias/Inquirer.js/issues/293#issuecomment-315944753, this change still keeps the desired behaviour of killing the process on CTRL-C, but it gives parent processes a chance to clean up.
> Better way to kill process

- lib/ui/bottom-bar.js
When I try to update my BottomBar by using `updateBottomBar` method and new text has more lines than previous text, content in console is overwritten. I make small fix to resolve this problem.
Code snippet to reproduce the problem:
```js
var BottomBar = require('../lib/ui/bottom-bar');
var ui = new BottomBar();
function startInterval() {
var i = 0;
var inter = setInterval(function () {
i++;
var table = 'line - 1\nline - 2\nline - 3\nline - 4\nline - 5\nProgress - ' + i + '%';
ui.updateBottomBar(table);
if (i % 20 === 0) {
ui.writeLog('work...');
}
if (i === 100) {
clearInterval(inter);
ui.updateBottomBar('Installation done!\n');
process.exit();
}
}, 50);
}
startInterval();
```
Result before fix:
Result after fix:
> Fix updating multiline BottomBar

- .gitignore
- README.md
@SBoudrias 
I have just published a new version of the `inquirer-command-prompt` plugin, adding an example and a few tests. I think it is ready.
> Adding inquirer-command-prompt to the plugins list

- lib/utils/screen-manager.js
This bug can reproduce in [this case](https://github.com/LitoMore/inquirer-chalk-pipe/blob/89502b9c7e6ce194e155455d8c7999f8f0524ae3/index.js#L60).
ANSI escape code should not be counted in the length.
**Expected behavior**
**Actual behavior**
**How to review this pull reuqest**
```bash
$ git clone -b instant-preview https://github.com/LitoMore/inquirer-chalk-pipe.git
$ cd inquirer-chalk-pipe
$ npm install
$ node example.js
```
> Fix cursor behavior

- README.md
- lib/prompts/base.js
Added `prefix` and `suffix` options in questions objects
> Added `prefix` and `suffix` custom option

- lib/prompts/checkbox.js
- lib/prompts/expand.js
- lib/prompts/list.js
- lib/utils/paginator.js
- lib/utils/screen-manager.js
Prior to this, a list with multi-line items works erratically; the current selection might be off the screen, or the list height may vary depending on which items are selected.
As part of this, Paginator now takes an optional ScreenManager instance. Prompts have been updated accordingly.
I noticed this most clearly with yarn's upgrade-interactive feature. To demonstrate:
1. Clone the yarn repo.
2. Within it, run `yarn upgrade-interactive` in a window that's too small to display the resulting table.
3. The current selection is off the top of the screen, and scrolling through the list doesn't work great in general.
The improvement can also be noticed by running [examples/long-list.js](https://github.com/SBoudrias/Inquirer.js/blob/651a569ccf37a8d8dd6ae4f348c414bab3649c19/examples/long-list.js …
> Paginator now handles multiple lines

- README.md
- examples/rx-observable-array.js
- examples/rx-observable-create.js
- lib/inquirer.js
- lib/prompts/editor.js
- lib/ui/prompt.js
- lib/utils/events.js
- lib/utils/utils.js
- package.json
- test/specs/inquirer.js
- yarn.lock
Hello, this pull request upgrades RxJS to version 5
> upgrade to RxJS 5

- lib/prompts/editor.js
Fixes #637 
`forEach` now returns a promise instead of a disposable subscription (therefore `.dispose()` does not exist)
> Correct subscription method

- README.md
- lib/prompts/input.js
- test/specs/prompts/input.js
> Apply optional transformer to input before accepted

- README.md
The Boolean type was omitted from the documentation for the `default` property, but it's a valid type when using `confirm`.
> Add 'Boolean' as option type to documentation of default

- lib/inquirer.js
- lib/prompts/number.js
- test/helpers/fixtures.js
- test/specs/prompts/number.js
Creates a convenient prompt specifically for getting numbers as input from the user. If the user input's something that is not a number, a default value is returned if it exists or `NaN` if no default was specified.
> Adds a NumberPrompt type for convenience (#654)

- lib/prompts/base.js
Addressing issue #635, this PR displays `[hidden]` as the default value instead of displaying the actual password, when applicable. The message is consistent with text displayed when the password is masked.
> Hide default values for passwords

- README.md
- lib/prompts/base.js
- test/specs/api.js
Following the style of wizards like `npm init` (see [PromZard](https://github.com/npm/promzard) and its precedents).
> Use name as default message

- README.md
Hello! I made this plugin prompt and I'd like to add it to the README. It's an input prompt with input suggestions.
Thanks!
> Add inquirer-prompt-suggest plugin to README

- README.md
A plugin I wrote when I couldn't find a robust directory selection prompt.
Allows fast file and/or directory selection using fuzzy autocomplete.
Might be useful for someone else.
> Add inquirer-fuzzy-path to README

- .travis.yml
- README.md
- package.json
- packages/inquirer/package.json
- packages/inquirer/yarn.lock
- yarn.lock
Codecov seems to have better support for merging many coverage reports. This will be useful while we're maintaining the old project at the same time as the refactor.
> Replace coveralls with codecov

- packages/inquirer/lib/prompts/input.js
- packages/inquirer/test/specs/prompts/input.js
~~Strip surrounding quotes from input value; enable empty values~~
As mentioned a loooong time ago in #108, there's currently no way to input an empty value for an input with a default value.
~~But what if we allowed users to put quotes around their input values the way you would when setting a bash variable? And then the value would be set to the unquoted value.~~
~~In other words, when a user enters `"foo"` the value would be set to `foo` (without quotes).~~
~~This feels like expected behavior to me, and it would enable an empty value for an input with a default value, because `""` would become an empty string.~~
~~Is this too magical or unexpected?~~
~~Would it be better to simply treat a value of `""` or `''` as a special case that should be transformed to an empty string?~~
I think …
> Allow empty input by removing default if user enters backspace on empty input

- packages/inquirer/lib/prompts/checkbox.js
fixes #479 
There is inconsistency between list and checkbox selected line. It is highlighted in list and ignored in checkbox module. It is hard to follow what item is currently selected, when there are to many similar items with checkboxes. This fix changes code in order to highlight selected line with cyan color.
> Added highlight for selected line in checkbox

- packages/inquirer/package.json
Right now, the npm `README` of inquirer is empty, so it looks like you're looking at the wrong module
I've added two npm scripts:
- Just before publishing, the `README` from `./` is copied to `./packages/inquirer`
- Just after publishing, that file is deleted
That should fix the problem
> Add README file to 'inquirer' npm package

- README.md
- Move logo to the top-right of the readme doc.
- Use absolute URL for the logo.
> Adjust logo position

- README.md
This PR adds the `inquirer-s3` plugin in the documented list of available plugins for Inquirer.
> Add inquirer-s3

- packages/inquirer/examples/long-list.js
This `paginated` option only exists in this example, but nowhere in the code. It was removed in https://github.com/SBoudrias/Inquirer.js/pull/55.
> Remove paginated option from example

- packages/inquirer/lib/prompts/base.js
Fix for #805 by removing all event listeners on `prompt.ui.close()`.
In the repro (https://github.com/jared-hexagon/inquirer-memory-leak-repro) I `npm link`ed my fork and the `MaxListenersExceededWarning` warning never shows up.
> Remove all event listeners on close to avoid memory leak

- packages/inquirer/lib/prompts/base.js
Investigation in [this comment](https://github.com/SBoudrias/Inquirer.js/pull/808#issuecomment-504183694)
Fixes #811
> Revert "Remove all event listeners on close to avoid memory leak (#808)"

- README.md
Hi:
I write a prompt `inquirer-file-tree-selection-prompt`, it's used for select a file or directory in a file tree, now I add it to your README.md, can u merge it? thx~
regards anc95
> feat: add inquirer-file-tree-selection-prompt readme

- packages/core/package-lock.json
- packages/core/package.json
- packages/inquirer/package-lock.json
- packages/inquirer/package.json
https://snyk.io/blog/snyk-research-team-discovers-severe-prototype-pollution-security-vulnerabilities-affecting-all-versions-of-lodash/
> Upgrade lodash to 4.17.12 to Fix Vulnerability

- packages/inquirer/lib/utils/events.js
In our CLI we capture SIGINT events and cancel any active prompt when this happens.
I noticed that when we do that, Inquirer leak the prompts, 
This happens because `rl` event streams (created when calling `observe(this.rl)`) never complete, thus causing underlying streams not to complete as well.
> close keypress stream when rl close

- packages/inquirer/lib/objects/choices.js
- packages/inquirer/test/specs/objects/choices.js
This fixes a bug in the following scenario:
- a new Choices is initialised, with one of the items being `disabled: true`
- `choices.push('item')` is used
In this situation, the realChoices/realLength of the Choices becomes incorrect, as disabled items weren't being filtered out of the list in the `push` function, only in the `constructor`. 
I've also added the necessary changes to the existing test.
> Bugfix: Choices.push() breaks index if a disabled item was already in the Choices

- packages/inquirer/lib/prompts/rawlist.js
- packages/inquirer/test/specs/prompts/rawlist.js
Sorry about that removing some features. And I have re-added the features that doesn't need to be removed. And also fix the prettier warning on the CI. please take a check. Thanks.
> fix multi rawList bug (#861)

- packages/inquirer/lib/ui/baseUI.js
Fixes https://github.com/SBoudrias/Inquirer.js/issues/767.
> Workaround node.js bug that closes main input and output stream.

- packages/inquirer/lib/ui/baseUI.js
@SBoudrias, please publish a reverted 7.0.3.
And this PR as an pre-release or beta if possible.
> Workaround node.js bug with readline

- README.md
- packages/inquirer/lib/inquirer.js
- packages/inquirer/test/specs/inquirer.js
> Produce error on prompt in non-tty environment.

- packages/inquirer/lib/inquirer.js
- packages/inquirer/lib/ui/prompt.js
- packages/inquirer/test/specs/inquirer.js
Fixes problem identified here: https://github.com/SBoudrias/Inquirer.js/pull/891#issuecomment-593304435 by moving TTY check to immediately before question is asked.
> Fix bug with non-tty checks and when.

- packages/inquirer/lib/inquirer.js
- packages/inquirer/lib/ui/baseUI.js
- packages/inquirer/lib/ui/prompt.js
- packages/inquirer/test/specs/inquirer.js
- Move tty check to setupReadlineOptions
- Add skipTTYChecks
- Enable skipTTYChecks by default for 7.x behavior stability.
Fixes https://github.com/SBoudrias/Inquirer.js/issues/902.
> Revert tty behavior for inquirer 7.x

- packages/confirm/index.js
The `@inquirer/confirm` value is formatted twice, on keypress and once done for display:
https://github.com/SBoudrias/Inquirer.js/blob/32ee96f8ffa96198734c46faf86340bc36878914/packages/confirm/index.js#L13-L14
https://github.com/SBoudrias/Inquirer.js/blob/32ee96f8ffa96198734c46faf86340bc36878914/packages/confirm/index.js#L24-L25
This means the final formatted value is always `yes`, even if the entered value is `no`:
(callback value is correct, as it is not called with the formatted value.)
---
This PR removes the second formatting, thus fixing the issue:
> Fix @inquirer/confirm formatted output value

- packages/core/index.js
- packages/core/lib/Paginator.js
- packages/core/lib/screen-manager.js
- packages/core/lib/utils.js
- packages/inquirer/lib/objects/choice.js
- packages/inquirer/lib/objects/choices.js
- packages/inquirer/lib/prompts/base.js
- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/lib/prompts/confirm.js
- packages/inquirer/lib/prompts/expand.js
- packages/inquirer/lib/prompts/list.js
- packages/inquirer/lib/prompts/rawlist.js
- packages/inquirer/lib/ui/baseUI.js
- packages/inquirer/lib/ui/bottom-bar.js
- packages/inquirer/lib/ui/prompt.js
- packages/inquirer/lib/utils/paginator.js
- packages/inquirer/lib/utils/screen-manager.js
- packages/inquirer/lib/utils/utils.js
**What's the problem this PR addresses?**
- Inquirer is currently loading lodash through the main entrypoint which makes it impossible for webpack to treeshake the unused code.
- Yarn is using Inquirer in its cli and, because of this, is shipping a lot of unnecessary code that we don't need in our bundle.
Compared to the other PRs that attempted to tackle this in the past (https://github.com/SBoudrias/Inquirer.js/pulls?q=is%3Apr+is%3Aclosed+lodash+module) this PR doesn't use the per method packages (they're deprecated and didn't help; https://lodash.com/per-method-packages) but instead requires the used methods directly. This will get rid of unused code and potentially help startup times as there is less code to process.
I made the diff as small as possible which is why I construct a `_` …
> Only mport used lodash methods

- packages/inquirer/examples/long-list.js
- packages/inquirer/lib/objects/choices.js
- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/lib/prompts/list.js
- packages/inquirer/test/specs/prompts/checkbox.js
- packages/inquirer/test/specs/prompts/list.js
here is a gif scrolling through a list with 200 multiline options - notice there are no cursors and it skips a huge chunk of choices.
Fixes https://github.com/SBoudrias/Inquirer.js/issues/494
- rebased @Ntag branch - https://github.com/NTag/Inquirer.js/commit/bc88006157a5723b34ed123e24681b138eab9f49
- added support for non-strings
- added comments for reader
> fix multiline in list and checkbox

- packages/inquirer/examples/long-list.js
- packages/inquirer/lib/prompts/list.js
- packages/inquirer/lib/prompts/rawlist.js
- packages/inquirer/lib/utils/paginator.js
- packages/inquirer/test/specs/prompts/list.js
- packages/inquirer/test/specs/utils/paginator.js
Follow up to https://github.com/SBoudrias/Inquirer.js/pull/925
I'm not sure if I should have changed the Paginator in packages/core. It seems like a copy, and it seems like this repo is moving toward a monorepo style, but I think the one in inquirer/utils that I've changed will fix the actual problem so I'll leave it to the maintainers to copy these changes in, unless you want me to do it.
> fix: paginator works with loop:false

- README.md
- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/test/specs/prompts/checkbox.js
I spent quite a long time figuring out why `loop: false` didn't work in checkbox prompts.
Turns out it wasn't implemented.
Here's my go at it. Fixes: #944
> feat: add loop: false for checkbox type prompts

- packages/core/package-lock.json
- packages/core/package.json
- packages/inquirer/package-lock.json
- packages/inquirer/package.json
Hi ! :wave: 
I don't know why Snyk missed it ([see their website](https://snyk.io/vuln/npm:lodash)), but there's currently an npm advisory to upgrade Lodash to 4.17.19 or later : https://www.npmjs.com/advisories/1523
> chore(deps): bump lodash to 4.17.19

- README.md
I had to look into the source code to find out that providing already answered questions was as easy as filling them in the 2nd argument. That's why I had to do this PR to help save time to future users. I saw it even has tests so it looks like a very thought-out feature.
Hope this helps.
Great library!
> [docs] clarification about prompt method. 

- README.md
- packages/editor/index.js
With these changes, it is possible to add an extension to the tmp file used by the editor in order to enable syntax highlighting etc.
This PR fixes issue #914
> Add possiblity to specify extension in editor (fixes #914)

- packages/inquirer/lib/prompts/rawlist.js
Addresses 
https://github.com/SBoudrias/Inquirer.js/issues/929
https://github.com/SBoudrias/Inquirer.js/issues/889
> fix: rawlist displays 'value' instead of 'short' after selection

- package.json
- packages/inquirer/package.json
- yarn.lock
Following commit:
- Bump dependencies: [`ff4e89bd629894eabf523bad5247dfced45440c1`](https://github.com/SBoudrias/Inquirer.js/commit/ff4e89bd629894eabf523bad5247dfced45440c1)
Introduced two breaking version updates for:
- chalk-pipe@5
- Moved to ESM
- Breaks `./packages/inquirier/examples/input.js`
- husky@5
- New Install requirements and migration
- Breaks `postinstall` and `lint-staged`
This PR resets back to migrate to both at a later date.
> downgrade: ⬇️ chalk-pipe@4, husky@4 (major bumps breaking)

- packages/inquirer/lib/ui/prompt.js
- packages/inquirer/test/specs/inquirer.js
I think it's worth to support a questions object, like this:
```js
const { foo, bar } = await inquirer.prompt({
foo: {
message: '...',
default: '...',
},
bar: {
default: '...',
}
}):
```
it looks better imo, `{ foo, bar }` visually matches the corresponding keys in the question object
and object literals keys are ordered (as long as they're not numeric)
This PR detects such an object, safely normally, since a question should contain a `name` prop, there can't be a conflict with a single question object
> Handle questions as a plain object {[name]: question}

- packages/inquirer/lib/prompts/base.js
- packages/inquirer/lib/prompts/input.js
- packages/inquirer/test/specs/prompts/number.js
The number prompt wants to use the default value if the input was invalid, however after a keypress (and if the default value is truthy) the default gets cleared. This is done so the default value is not rendered in the prompt anymore, see: https://github.com/SBoudrias/Inquirer.js/pull/719
This PR changes the logic so that instead of clearing the default value it sets a new state called "touched". We can then use this state to hide the default value from the rendered prompt.
Updated the relevant test so it would have failed before.
> fix: retain number prompt default

- packages/inquirer/lib/prompts/base.js
- packages/inquirer/lib/prompts/password.js
- packages/inquirer/test/specs/prompts/password.js
The issue starts in [base.js line 100](https://github.com/SBoudrias/Inquirer.js/blob/9bee59b9/packages/inquirer/lib/prompts/base.js#L100):
```javascript
const validation = submit.pipe(
flatMap((value) => {
this.startSpinner(value, this.opt.filteringText);
return asyncFilter(value, self.answers).then(
(filteredValue) => {
this.startSpinner(filteredValue, this.opt.validatingText);
```
My solution was to modify `startSpinner()` to call a new method `getSpinningValue()`, which defaults to a passthrough.
```javascript
startSpinner(value, bottomContent) {
value = this.getSpinningValue(value);
// ...
```
```javascript
getSpinningValue(value) {
return value;
}
```
Then I modified `PasswordPrompt` to override that method to return the same as when it renders normally. I moved some code in …
> do not display password on async filter/validation, fixes #1022

- packages/inquirer/lib/prompts/base.js
When setting the `prefix` option to an empty string (effectively trying to remove it) the prompt still displays and empty space at the beginning of the message.
This PR should address that.
**Steps to reproduce**
```js
import inquirer from 'inquirer';
await inquirer.prompt([
{
type: 'confirm',
name: 'confirm',
prefix: '',
message: 'Confirm test',
},
]);
```
**Expected result**
```bash
Confirm test (Y/n)
```
**Actual result**
```bash
Confirm test (Y/n)
```
> Add prefix extra space only when not empty

- packages/inquirer/lib/prompts/rawlist.js
Fix of #1042
At the moment of pressing Enter key while Error being shown, `index` (1) [which](https://github.com/SBoudrias/Inquirer.js/blob/8e0b3d4c76bcf5c970936fec2561d3cc7964abb5/packages/inquirer/lib/prompts/rawlist.js#L122) comes as an argument equals to empty string.
At the same time `this.selected` equals to `undefined` (2) [here](https://github.com/SBoudrias/Inquirer.js/blob/8e0b3d4c76bcf5c970936fec2561d3cc7964abb5/packages/inquirer/lib/prompts/rawlist.js#L126).
```
getCurrentValue(index) { // (1)
if (index == null) {
index = this.rawDefault;
} else if (index === '') {
index = this.selected; // (2)
} else {
index -= 1;
}
const choice = this.opt.choices.getChoice(index); // (4)
return choice ? choice.value : null;
}
```
This happens because (3) …
> fix of #1042 rawlist throw

- packages/inquirer/lib/prompts/rawlist.js
Fix of #1042 #1045 
For compatibility with older versions of `node` ES2020 operator been replaced with explicit check.
```
this.selected =
this.selected !== null && this.selected !== undefined ? this.selected : -1;
```
> compatibility fix #1042

- .prettierrc
- packages/inquirer/lib/prompts/checkbox.js
- packages/inquirer/test/specs/inquirer.js
This keeps the checkbox hint/instructions on screen and adds `, and <enter> to proceed` to the hint.
It also allows linting and testing to occur on Windows.
Example:
Fixes #1031
> feat: checkbox hints now stay on screen until enter is pressed

- packages/core/index.js
- packages/inquirer/lib/objects/choice.js
- packages/inquirer/lib/objects/choices.js
- packages/inquirer/lib/prompts/confirm.js
- packages/inquirer/lib/prompts/expand.js
- packages/inquirer/lib/prompts/list.js
- packages/inquirer/lib/prompts/rawlist.js
- packages/inquirer/lib/ui/baseUI.js
- packages/inquirer/test/helpers/readline.js
- packages/inquirer/test/specs/inquirer.js
- noop
- extend
- find
- findIndex
- isNumber
> fix: Remove more lodash stuff

- packages/core/lib/Paginator.js
- packages/inquirer/lib/ui/bottom-bar.js
- packages/inquirer/test/specs/api.js
- packages/inquirer/test/specs/prompts/checkbox.js
- packages/inquirer/test/specs/prompts/confirm.js
- packages/inquirer/test/specs/prompts/editor.js
- packages/inquirer/test/specs/prompts/expand.js
- packages/inquirer/test/specs/prompts/input.js
- packages/inquirer/test/specs/prompts/list.js
- packages/inquirer/test/specs/prompts/number.js
- packages/inquirer/test/specs/prompts/password.js
- packages/inquirer/test/specs/prompts/rawlist.js
There are 3 remaining files after this gets merged.
They are slightly more annoying and harder to refactor out cuz of things like `Lodash 'where' clause` in `_.get` for example.
i would have use optional chaining...
Will leave the rest to you to decide what to do with it:
> lodash almost gone

- packages/inquirer/package.json
Hello 👋 
I noticed the engines field doesn't match the latest release https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%408.0.0
> fix: bump engines field to Node.js>=12

- packages/inquirer/examples/regex-validate-input.js
I hope you don't mind. I thought examples/ could do with a few more basic prompts in there. This is the first of a few I was thinking of. I will PR the others when I get time.
> chore: add example for a simple regex match on an input

- packages/inquirer/lib/prompts/rawlist.js
This fixes a bug in the input processing of "rawlist". To reproduce the bug:
- Run a rawlist configuration
- Use the arrow keys to select an item
- Then use the number keys to enter a specific item, and press enter
- Get an "invalid option" error
Because the arrow keys record the selected index on the input line, when the user enters a specific index, an ultimately invalid index is processed by the code.
This works around that by not using the input line to record the selected index when using arrow keys. Instead it records the selected index in a private variable.
> fix input of "rawlist"

- README.md
Available at https://github.com/lnquy065/inquirer-interrupted-prompt
Turning any existing inquirer and its plugin prompts into prompts that can be interrupted with a custom key.
> Add inquirer-interrupted-prompt plugin into readme

- package.json
- packages/core/lib/utils.js
- packages/core/package.json
- packages/inquirer/examples/terminal-link.js
- packages/inquirer/lib/utils/screen-manager.js
- packages/inquirer/package.json
- yarn.lock
This PR addresses incorrect line wrapping with `terminal-link`. It does so by employing the `wrap-ansi` npm.
Fixes #1014
Fixes #304
To the reviewers: I wasn't sure whether we should pass the [hard](https://github.com/chalk/wrap-ansi#hard) option to `wrap-ansi`:
> By default the wrap is soft, meaning long words may extend past the column width. Setting this to true will make it hard wrap at the column width.
If inquirer needs hard wrapping (in which case I assume wrap-ansi may split long words at arbitrary points in order to avoid overflow), we can easily add that to this PR.
> fix: port breakLines to wrap-ansi

- packages/inquirer/lib/prompts/number.js
- packages/inquirer/test/specs/prompts/number.js
I added a support for negative float numbers into number prompt by adjusting the regex. Also I added the unit test for this case.
> Support negative float numbers

- packages/core/lib/utils.js
- packages/inquirer/lib/utils/screen-manager.js
[This PR](https://github.com/SBoudrias/Inquirer.js/pull/1106) updated `breakLines` to use `wrap-ansi`. However, in doing so, we broke the paginator. It assumes that the return value will be of the same length as the original array, but that broken lines will be subarrays.
> fix: breakLines regression versus paginated content

- packages/core/src/lib/Paginator.ts
- packages/core/src/lib/index.d.ts
index.d.ts was added for the library **cli-width** which does not provide types (no @types/cli-width package present either). 
Not sure if this is the way to go.
Looking for feedback on this, so I can start migrating other files too. Thanks.
PS - While tinkering with files with export, building with tsc packages/core/src/lib/key.ts and running node packages/core/src/lib/key.js throws 
`exports.__esModule = true;`
`ReferenceError: exports is not defined`
Any idea on how I should go about tackling this (or ignoring it)?
> Paginator.js migrated to Paginator.ts

- packages/input/src/index.ts
- packages/password/src/index.ts
- packages/rawlist/demo.ts
- packages/rawlist/package.json
- packages/rawlist/src/index.ts
- packages/rawlist/tsconfig.json
#1101 continuation
Some other things to be noted
- stdio in password is now optional
Correct me if I'm wrong but I don't fully understand the difference in the old inquirer and the new separate packages and why do they differ in options available - for example filter doesn't seem to be supported on any prompt types. Is the new core a WIP?
> @inquirer/rawlist TS migration

- packages/expand/demo.ts
- packages/expand/package.json
- packages/expand/src/index.ts
- packages/expand/tsconfig.json
https://github.com/SBoudrias/Inquirer.js/issues/1101 continuation
> @inquirer/expand TS migration

- packages/checkbox/src/index.ts
It is now possible to customize the instructions in the checkbox type, for https://github.com/SBoudrias/Inquirer.js/issues/1138
Instructions support for string or boolean type.
1.When instructions set to false, help tip disappear:
```js
{
type: 'checkbox',
message: 'Select a package manager',
instructions: false,
choices: [
{ name: 'npm', value: 'npm' },
{ name: 'yarn', value: 'yarn' },
{ name: 'jspm', value: 'jspm', disabled: true },
],
}
```
2.When instructions set to string, help tip is customized:
```js
{
type: 'checkbox',
message: 'Select a package manager',
instructions: '空格单选，a键全选，i键取消选择',
choices: [
{ name: 'npm', value: 'npm' },
{ name: 'yarn', value: 'yarn' },
{ name: 'jspm', value: 'jspm', disabled: true },
],
}
```
2.When instructions are not set or set other values, help tip …
> feat: custom instructions in the checkbox type

- packages/checkbox/src/index.ts
If the prefix property in the checkbox type is not set to any value, it will show `undefined`, which looks weird, so i think need to set a default value.
> feat(checkbox): the initial value of prefix

- packages/core/src/lib/utils.ts
When the text is too long and spans lines, all keys that can cause interaction will cause the message to be displayed repeatedly.
The bottom is a reproduction of the bug:
1.checkbox(version: `@inquirer/checkbox@0.0.23-alpha.0`):
2.select(version: `@inquirer/select@0.0.22-alpha.0`):
The rest also have this bug, I didn't record it as a gif.
System Info:
NodeJS 16.10.0
windows 10
> fix: message renders repeatedly when text spans lines

- README.md
- packages/inquirer/examples/editor.js
- packages/inquirer/lib/prompts/editor.js
- packages/inquirer/test/specs/prompts/editor.js
As requested in #1149, editor prompt always requires the user to press enter before launching the system editor, this pr adds a flag `waitUserInput` (default: `true`) that if set to `false` skips the user confirmation.
> feat(editor): add flag waitUserInput

- packages/checkbox/src/index.ts
Complement the default help tip message like the old version, as follows:
> feat(checkbox): complement the help tip message

- packages/core/src/lib/screen-manager.ts
Getting a similar issue to #62 for the new Inquirer.
Calling `end()` like before seems to fix it.
> Call stream end to trigger cleanup

- packages/checkbox/src/index.ts
When key `a` or `i` is pressed, the disabled selection item is also optional.
Reproduction address: https://stackblitz.com/edit/node-q8w1he?file=index.js
> fix(checkbox): optional when the selection is disabled

- packages/select/src/index.mts
I have a project that needs to use a custom disabled text for the `Select` type. As shown below
> feat(select): customize the display text for disabled text

- README.md
- packages/confirm/README.md
- packages/inquirer/examples/pizza.js
- packages/inquirer/lib/prompts/base.js
- packages/inquirer/lib/prompts/confirm.js
- packages/inquirer/test/specs/prompts/confirm.js
PR for the [Feature request: Support for transformer function for confirm type #1207](https://github.com/SBoudrias/Inquirer.js/issues/1207)
The following changes are made:
- Updated the pizza.js file in the examples of confirm prompt.
- Added the transform default function to the Base class to extend this feature to other prompts if and when required. By default, it will return the value as is.
- Updated confirm.js file to allow support of transforming the output, if the user has provided a transformation function.
- Added a test case for this feature as well.
> added transform feature for confirm prompts

- tools/rename-ext.mts
Fixes #1218 
This is a quick fix for CommonJS files. We could consider using other tools in the future.
> Fix CommonJS file content

- .github/workflows/main.yml
- packages/checkbox/package.json
- packages/confirm/package.json
- packages/core/package.json
- packages/editor/package.json
- packages/expand/package.json
- packages/input/package.json
- packages/password/package.json
- packages/prompts/package.json
- packages/rawlist/package.json
- packages/select/package.json
- packages/testing/package.json
- packages/type/package.json
- tools/setup-packages.mts
The `yarn test` script will fail on Node.js 20. This is because:
- https://github.com/TypeStrong/ts-node/issues/1997
I changed the command to `node --loader ts-node/esm` for running scripts.
I also added `--no-warnings=ExperimentalWarning` to suppress those experimental warnings.
- Add Node.js 20 to GitHub Actions
- Change `fix-ext` to `node --no-warnings=ExperimentalWarning --loader ts-node/esm ../../tools/rename-ext.mts`
> Support Node.js 20

- packages/core/package.json
- packages/core/src/index.mts
- packages/core/src/lib/Separator.mts
- packages/prompts/package.json
- packages/prompts/src/index.mts
- packages/select/README.md
- packages/select/demo.mts
- packages/select/src/index.mts
Initial solution on https://github.com/SBoudrias/Inquirer.js/issues/1230
If this solution works, I will add it to the rest of the prompts.
> feat: support separator in select prompt

- packages/prompts/README.md
The `npx inquirer-demo --package=@inquirer/demo` only work when the user is under the project directory and executed `yarn install`.
The `npx @inquirer/demo` will be better. This command can be executed anywhere. The only requirement is the Node.js runtime.
**Hint:**\
The package will be cached to their local when running `npx @inquirer/demo`. So if we want our users always get the latest version of the demo, the command should be `npx @inquirer/demo@latest`.
> Fix demo command

- packages/prompts/src/index.mts
This exposes all core functions to `@inqurier/prompts`.
I believe some people will use our built-in prompts and their self-made prompts at the same time.
In this case, allowing them access to our `core` functions with `inquirer/prompts` is better.
In the future, we can provide and expose more utility functions in this way.
> prompts: Expose all core functions

- packages/confirm/src/index.mts
- packages/inquirer/lib/prompts/confirm.js
- packages/inquirer/test/specs/prompts/confirm.test.js
Resolves #1239
I will research how other confirm prompts like `apt` and `ssh` work before marking it as ready.
|Input|TrueConfirm output|FalseConfirm output|
|:--|:--|:--|
|foo bar|false|false|
|Input|TrueConfirm output|FalseConfirm output|
|:--|:--|:--|
|foo bar|true|false|
> Fix (Confirm): Set every other string fallback to default value

- packages/core/core.test.mts
- packages/prompts/README.md
Related to https://github.com/SBoudrias/Inquirer.js/issues/816#issuecomment-1575193594.
I also added a test case to cover `answer.cancel()` running multiple times.
> Use `await setTimeout()` for timeout example

- packages/confirm/README.md
- packages/confirm/src/index.mts
Not sure how this issue hasn't been raised yet, but the regex in the confirm prompt is matching *any* input because of the question mark.
**With question mark (current):**
With the question mark, the regex matches the beginning of a line and the pattern `y|yes` 0 or 1 times. Since there will always be the beginning of a line and the `y|yes` pattern is optional, it is always `true`.
**Without question mark (fixed):**
With*out* the question mark, the regex matches the beginning of a line followed by the **required** pattern `y|yes`, which properly returns the right value.
Additionally, the message in the example - `"Enter your name"` - makes no sense for a confirm prompt. I just went for `"Continue?"` instead.
> Fix regex and documentation issues with confirm prompt

- .eslintrc.json
- packages/inquirer/test/helpers/readline.js
Enforce that every-time we disable a rule to specify what rule it is for better legibility.
Also enforce this with the unicorn rule -> https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/no-abusive-eslint-disable.md
> nit: enforce adding the rule to disable via unicorn no-abusive-eslint

- packages/inquirer/lib/ui/bottom-bar.js
- packages/inquirer/package.json
- yarn.lock
Fixes #1266
`through` is still pulled in via some dev deps, but at least the direct dep is now maintained :-)
> chore: replace `through` with `@ljharb/through`

- packages/inquirer/lib/objects/choices.js
Changed  `import _ from 'lodash';`
to
```
import filter from 'lodash/filter.js';
import map from 'lodash/map.js';
```
This reduces the bundle size and will help bundlers with tree shaking.
> chore: directly import only needed lodash modules

- packages/password/src/index.mts
In the [password config](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/password),  the transformer and default attributes should not be included. 
The original code inherited the type of the input config, I used Omit to remove these two attributes so that users can receive more user-friendly and accurate prompts.
> Type: password config type

- package.json
- packages/checkbox/package.json
- packages/confirm/package.json
- packages/core/package.json
- packages/editor/package.json
- packages/expand/package.json
- packages/input/package.json
- packages/password/package.json
- packages/prompts/package.json
- packages/rawlist/package.json
- packages/select/package.json
- packages/testing/package.json
- packages/type/package.json
- tools/fix-ext.mjs
- tools/setup-packages.mjs
Related to https://github.com/SBoudrias/Inquirer.js/pull/1279#issue-1840862449.
Here is the build time difference:
|Before|After|
|:-:|:-:|
|![](https://github.com/SBoudrias/Inquirer.js/assets/8186898/78dd6537-5379-42e7-8bc6-bd5798732915)|![](https://github.com/SBoudrias/Inquirer.js/assets/8186898/69e9615e-1c5b-4441-a973-bd6480466713)|
> Migrate `.mts` scripts to `.mjs`

- packages/core/core.test.mts
- packages/core/src/index.mts
Rationale: State management through the scoped variables did (and could again, or might still do so in narrow cases) cause leaks in context around async operations and cleanup phases. I think using AsyncLocalStorage might improve this caveats by ensuring a stable context.
> Refactor (Core): Move from scoped variables to node built-in AsyncLocalStorage

- .eslintrc.json
Adds an eslint rule to avoid importing the whole of lodash
Relates to [comments](https://github.com/SBoudrias/Inquirer.js/pull/1271#issuecomment-1656245120) in #1271
> chore: add rule to avoid importing the whole of lodash

- packages/core/src/lib/use-prefix.mts
- tsconfig.json
Typescript 5.2.2 somehow broke the CJS import of cli-spinners. I turned on the es module interop option, and the output seems to mock the `.default` properly.
Fix #1297
Close #1298
> Fix (core): Fix cli-spinner imports with changes to tsconfig.json

- packages/checkbox/checkbox.test.mts
- packages/checkbox/src/index.mts
This is tied to refactors related to #1289 
In this PR, we disambiguate between a choice and an item in the list, and between the cursor position and the active index, and add utility methods. We also extract out the render function. In addition, we simplify `isSelectableChoice` into `selectable`, a refinement function which does not work on `undefined`, and instead handle undefined in the more idiomatic way (which doesn't need comments).
> Refactor checkbox

- packages/select/src/index.mts
This is tied to refactors related to #1289
In this PR, we disambiguate between a choice and an item in the list, and between the cursor position and the active index, and add utility methods. We also extract out the render function. In addition, we simplify isSelectableChoice into selectable, a refinement function which does not work on undefined, and instead handle undefined in the more idiomatic way (which doesn't need comments).
> Refactor select

- packages/core/README.md
- packages/core/core.test.mts
- packages/core/src/index.mts
- packages/core/src/lib/hook-engine.mts
- packages/core/src/lib/use-memo.mts
- packages/core/src/lib/use-state.mts
Related to #1289; we `useMemo` hook for Inquirer has a use case. So let's add it in!
Internal change: This PR also fixes the typing around the internal `withPointer` utility to increase the core type-safety.
> Feat (Core): Introduce a useMemo hook

- packages/password/package.json
- packages/password/password.test.mts
- packages/password/src/index.mts
- yarn.lock
Extracted the core rewrite from #1334 (cc @matteosacchetto).
Since this other PR is blocked on finding the right key-binding, I want to unblock other work (like the theme branch) I punted upon to not heavily conflict with the rewrite. Separating the rewrite should reduce the friction 🤞🏻
> Feat: Implement password prompt as a standalone prompt

- packages/checkbox/src/index.mts
- packages/confirm/src/index.mts
- packages/core/core.test.mts
- packages/core/src/index.mts
- packages/core/src/lib/create-prompt.mts
- packages/editor/src/index.mts
- packages/expand/src/index.mts
- packages/input/src/index.mts
- packages/password/src/index.mts
- packages/prompts/README.md
- packages/rawlist/src/index.mts
- packages/select/src/index.mts
Planning to remove built-in support for async/functions `message`.
The reasons are kinda simple:
1. I don't want to new Inquirer to be a state/flow management library (that's better done elsewhere; usually with simple Node/JS built-in)
2. The UX is bad; and not been a priority to handle due to point 1
3. When starting the rewrite, I had a few more wrapped logic there, but it was slowly all removed to be inside each prompts. So only `message` is left, and shows how it didn't match the design goals of the new API.
Do let me know if you think otherwise. I'll leave this PR open for now and bundle with some other breaking changes.
> Breaking: Remove async message feature

- packages/checkbox/README.md
- packages/checkbox/src/index.mts
- packages/confirm/README.md
- packages/confirm/package.json
- packages/confirm/src/index.mts
- packages/core/README.md
- packages/core/src/index.mts
- packages/core/src/lib/make-theme.mts
- packages/core/src/lib/pagination/use-pagination.mts
- packages/core/src/lib/theme.mts
- packages/core/src/lib/use-prefix.mts
- packages/editor/README.md
- packages/editor/package.json
- packages/editor/src/index.mts
- packages/expand/README.md
- packages/expand/src/index.mts
- packages/input/README.md
- packages/input/input.test.mts
- packages/input/package.json
- packages/input/src/index.mts
- packages/password/README.md
- packages/password/package.json
- packages/password/src/index.mts
- packages/rawlist/README.md
- packages/rawlist/src/index.mts
- packages/select/README.md
- packages/select/src/index.mts
- packages/type/src/index.mts
- yarn.lock
This PR introduce theming capacity to Inquirer. This idea has been floating around multiple issues in the repo (#822, #1169, and others); but timing wasn't right for major API changes.
From prompts user perspective, the default prompts (and hopefully the custom ones) will take an optional `theme` object config. That'll define how things are rendered.
Prompts can define their own extension to the theme object for their unique rendering.
Theme-ability is introduce with the `makeTheme` small utility. A default theme is always applied, but can be extended with each prompts specific theming needs.
1. `@inquirer/core`: `usePrefix` interface changed
2. `@inquirer/confirm`: `prefix` config is removed in favour of `theme.prefix`
4. `@inquirer/checkbox`: `prefix` config is removed in favour of …
> [major] Introduce theming capacities

- packages/checkbox/checkbox.test.mts
- packages/checkbox/src/index.mts
- packages/core/core.test.mts
- packages/core/src/index.mts
- packages/core/src/lib/create-prompt.mts
- packages/core/src/lib/errors.mts
- packages/core/src/lib/hook-engine.mts
- packages/select/select.test.mts
- packages/select/src/index.mts
Fix #1368
TODO: I think I'd like to expose as `@inquirer/core/errors` (with export map)
> Feat: Throw custom errors and expose them from @inquirer/core

- packages/demo/demos/timeout.mjs
- packages/demo/index.mjs
- packages/prompts/README.md
The [Get Default Value After Timeout](https://github.com/SBoudrias/Inquirer.js/?tab=readme-ov-file#get-default-value-after-timeout) recipe didn't work for me since the process would wait until the timeout completed to exit.
I've updated the recipe to abort the timeout once the prompt has been answered.
> Chore: Update timeout example

- packages/input/src/index.mts
The cursor positions for inputs without a current value are incorrect.
Before:
https://github.com/SBoudrias/Inquirer.js/assets/8485687/66cf88b4-51dc-4d50-b32d-4237597c8659
After:
https://github.com/SBoudrias/Inquirer.js/assets/8485687/e1f60c5c-b3ac-4244-9092-d449c7b08294
> Fix input's cursor start

- packages/core/src/lib/screen-manager.mts
Various UI components would flicker upon being re-rendered. This fixes that by delaying screen clearing until necessary.
https://github.com/SBoudrias/Inquirer.js/assets/8485687/420c6e33-c234-4a09-ac8c-17bc989c8490
https://github.com/SBoudrias/Inquirer.js/assets/8485687/95cc031a-d263-4392-bb67-51e08955cd02
> Fix flickering

- packages/prompts/package.json
- packages/prompts/src/index.mts
- yarn.lock
Breaking change to `@inquirer/prompts` to stop exporting the core APIs from it.
This was proposed earlier by a PR, but it's been causing issue. Any breaking change to `@inquirer/core` becomes a breaking change to `@inquirer/prompts`, and for most users they'll only rely on prompts that receive UX upgrade.
So, I'm feeling pretty strongly about keeping both packages separated going forward.
1. Breaking changes to `@inquirer/core` are more frequent (larger API surface.) So they'll just be exposed to prompt authors. (as a proof, we're at v7 of `@inquirer/core`, vs v2 of most prompts)
2. Breaking changes to `@inquirer/prompts` means there's been a non-backward compatible change to a prompt public interface. Those are rare, so most of the time it'll be patch/minor updates to the UX that users …
> BREAKING: Stop exporting core APIs from @inquirer/prompts

- packages/prompts/README.md
I made a table multiple selection prompt for a project I am working on. Feel free to make comments to improve the prompt.
> Add inquirer-table-multiple community prompt

- .eslintrc.json
- packages/checkbox/src/index.mts
- packages/core/src/lib/use-ref.mts
- packages/core/src/lib/use-state.mts
- packages/editor/src/index.mts
- packages/expand/src/index.mts
- packages/input/src/index.mts
- packages/password/src/index.mts
- packages/rawlist/src/index.mts
- packages/select/src/index.mts
Review the typing of `useState` and `useRef` to handle being implicitly empty. Empty initialization will not raise errors anymore, and it'll automatically assume the value can be undefined.
This allow to reduce boilerplate, and arguably leads to more idiomatic code.
> Feat(core): Allow useState/useRef to initialize empty

- packages/prompts/README.md
https://github.com/th0r/inquirer-sortable-checkbox
> Add "sortable checkbox" to the list of custom prompts in README.md

- packages/inquirer/examples/editor.js
- packages/inquirer/lib/prompts/editor.js
- packages/inquirer/test/specs/prompts/editor.test.js
Fixes #1405, reverting the bugs introduced in [8328d65](https://github.com/SBoudrias/Inquirer.js/commit/8328d659466cce33f0f9171c9daf30927fa7de0d#diff-479a1e309f0fe42c909aa27d39f3e841147f0ea568e4238bf3635c457171b65aR29-R31) (the editor opens without defaults, and Inquirer renders text on top of in-terminal editors such as `vi`). 
The editor now opens only after `this.currentText` has been set, and the initial render does not occur if `waitUserInput` is false.
The previous tests for the editor prompt do not make use of the `default` property set in the editor fixture.  The message written to the temporary file and its expected contents are turned into test parameters `message` and `expectedAnswer`, respectively. Two additional test cases are added in which the test editor `writeBin` is …
> Fix: Open editor with default value

- packages/password/src/index.mts
This PR fixes a small inconsistency in the presentation of the password prompt.
In the previous implementation, the prompt was missing a space between the message and the value, when the value was empty.
This fixes that and also makes sure that if you use do not pass a mask there is not an additional space between the message and the helpTip
This ensures that the password prompt is consistent with the input prompt (which already implements a similar fix), and ensures that it is consistent with how the password prompt appeared before the "style customization" update (ex. v1.1.15)
> fix(password): ensure consistency in prompt appearence

- packages/inquirer/README.md
The new Inquirer package links to the old one, but as far as I can tell, the old one doesn't link to the new one.
Since the old package is still quite popular, it's probably a good idea to mention it isn't being actively developed anymore.
> Docs(inquirer): Link to new version on old version's README

- .github/workflows/codeql-analysis.yml
- packages/checkbox/package.json
- packages/confirm/package.json
- packages/core/README.md
- packages/core/package.json
- packages/editor/package.json
- packages/expand/package.json
- packages/input/package.json
- packages/inquirer/README.md
- packages/inquirer/package.json
- packages/number/package.json
- packages/password/package.json
- packages/prompts/README.md
- packages/prompts/package.json
- packages/rawlist/package.json
- packages/select/package.json
- packages/testing/README.md
- packages/testing/package.json
- tools/setup-packages.mjs
Replace references to master branch with main branch.
The default branch seems to have been renamed from master branch to main branch. However, some references are untouched and broken (e.g., "send us a PR adding it" link). This change replaces all occurrences of "master" with "main" except for other projects in ./packages/inquirer/README.md and screenshots under ./assets/screenshots.
```bash
$ git grep -e 'SBoudrias/Inquirer.js/.*/main' --name-only /workspaces/Inquirer.js | wc -l
18
$ git grep -e 'SBoudrias/Inquirer.js/.*/master' --name-only /workspaces/Inquirer.js | wc -l
0
```
```bash
$ git grep -e 'master' /workspaces/Inquirer.js ':!*.svg' | cat 
packages/inquirer/README.md:![autocomplete prompt](https://raw.githubusercontent.com/mokkabonna/inquirer-autocomplete-prompt/master/packages/ …
```
> Fix references to default branch

- packages/checkbox/README.md
- packages/confirm/README.md
- packages/editor/README.md
- packages/expand/README.md
- packages/input/README.md
- packages/number/README.md
- packages/password/README.md
- packages/rawlist/README.md
- packages/select/README.md
Making this change since `@inquirer/prompts` is the preferred option. And saw in the wild people potentially overcomplicating their setup using 4-5 individual packages.
> Chore(documentation): Update install and usage instructions to suggest @inquirer/prompts first

- .github/workflows/main.yml
Hoping cache will reduce duplication of builds.
Results: from ~7m20 to ~3m45 (comparison of 2 full turbo runs. When compiling TS it'll be slightly slower.)
> Chore: Run tsc first and cache on vercel before running tsc dependant jobs

- packages/core/src/lib/create-prompt.mts
This PR fixes the memory leak warning below
```
(node:2670733) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
at _addListener (node:events:591:17)
at WriteStream.addListener (node:events:609:10)
at WriteStream.Readable.on (node:internal/streams/readable:928:35)
at MuteStream.Stream.pipe (node:internal/streams/legacy:33:8)
at MuteStream.pipe (/xxxxx/node_modules/mute-stream/lib/index.js:73:18)
at Object.prompt …
```
> Fix(@inquirer/core): Destroy output stream on exit.

- packages/demo/demos/search.mjs
- packages/search/README.md
- packages/search/search.test.mts
- packages/search/src/index.mts
Adding a new feature set to the `search` prompt so it can double as an autocomplete helper. This will make it easier to implement progressive search prompts (like exploring a file system.)
This relies on 2 new behaviour:
1. `tab` key triggers an autocomplete of the selected choice `name` property into the search bar
2. Adding support for `validate` (I tend to stay away from adding validation to list type prompts, but I think this is a neat use-case.)
3. Pressing `enter` doubles as `tab` when the value doesn't match the search string and doesn't pass validation.
There's a demo you can run to try it out locally; run `yarn demo` from the root of the repository. Then select the `Search` demo option.
> Feat(@inquirer/search): Add autocomplete capacities to the search prompt

- packages/checkbox/README.md
- packages/checkbox/checkbox.test.mts
- packages/checkbox/src/index.mts
- packages/core/src/lib/Separator.mts
- packages/expand/README.md
- packages/expand/expand.test.mts
- packages/expand/src/index.mts
- packages/rawlist/README.md
- packages/rawlist/rawlist.test.mts
- packages/rawlist/src/index.mts
- packages/search/README.md
- packages/search/search.test.mts
- packages/search/src/index.mts
- packages/select/README.md
- packages/select/select.test.mts
- packages/select/src/index.mts
Ref #1527
Inquirer v9 & prior allowed choices to be array of strings. Given how widespread that pattern is, we should maintain this backward compatibility. It'll also simplify the work of folks migrating from `inquirer` to `@inquirer/prompts` with less code change.
> Fix(inquirer): Allow string choices (backward compat with v9 & prior)

- packages/core/src/lib/create-prompt.mts
- packages/type/src/inquirer.mts
1. Reduce amount of function calling each others to cleanup Inquirer.
2. Add manual `Promise.withResolvers()` utility to allow flattening the logic.
> Refactor(@inquirer/core) Cleanup the exit logic & promise constructor

- packages/inquirer/inquirer.test.mts
- packages/inquirer/src/index.mts
- packages/inquirer/src/types.mts
- packages/inquirer/src/ui/prompt.mts
Fixes https://github.com/SBoudrias/Inquirer.js/issues/1521
> feat(inquirer): add AbortSignal support

- packages/inquirer/inquirer.test.mts
- packages/inquirer/src/ui/prompt.mts
Related to https://github.com/SBoudrias/Inquirer.js/issues/1527
> fix(inquirer): adjust parameters

- packages/inquirer/inquirer.test.mts
- packages/inquirer/src/index.mts
- packages/inquirer/src/types.mts
- packages/inquirer/src/ui/prompt.mts
Related to https://github.com/SBoudrias/Inquirer.js/issues/1527.
> feat(inquirer): export types Question, DistinctQuestion and Answers

- packages/editor/README.md
- packages/editor/editor.test.ts
- packages/editor/src/index.ts
- packages/input/README.md
- packages/input/input.test.ts
- packages/input/src/index.ts
Applied to both `input` and `editor` prompts. In both prompt, the `keep` mode was, and stays, the default. The `clear` mode now becomes an option.
Fix #374
Fix #907
> Add `theme.validationFailureMode` option to control behaviour on validation failure

- packages/checkbox/README.md
- packages/confirm/README.md
- packages/core/README.md
- packages/editor/README.md
- packages/expand/README.md
- packages/input/README.md
- packages/inquirer/README.md
- packages/number/README.md
- packages/password/README.md
- packages/prompts/README.md
- packages/rawlist/README.md
- packages/search/README.md
- packages/select/README.md
- packages/testing/README.md
Proposal to replace HTML with only markdown.
Links in markdown do work on NPM, but can't test exactly the extent of their HTML support easily (also couldn't find specific documentation as to what's supported 😞)
[Changes visible here](https://github.com/SBoudrias/Inquirer.js/blob/sponsorship/links-for-npm/packages/prompts/README.md); main change is loosing the center alignment.
cc @ericdachen
> Fix(sponsorship): <a> HTML tags stripped on npmjs.com

- .github/workflows/main.yml
- integration/cjs/fixturePrompt.cjs
- integration/cjs/integration.test.cjs
- integration/esm/fixturePrompt.mjs
- integration/esm/integration.test.mjs
- packages/core/src/lib/create-prompt.ts
Skip assignment of
```js
Error.prepareStackTrace = _prepareStackTrace
```
when the value hasn't changed to avoid triggering a mutation error when Node flag `--frozen-intrinsics` is used.
https://nodejs.org/api/cli.html#--frozen-intrinsics
> Support Node's --frozen-intrinsics flag

- packages/prompts/README.md
Hello 👋
I have added the `@inquirer-cli` mention in the readme. I put it under the `Usage` section as I guess it counts as an alternative usage for `Inquirer.js`?
Happy to be told to move it further down. 😂
Jason
> doc: add `@inquirer-cli` mention in readme.

- packages/core/core.test.ts
- packages/core/src/lib/create-prompt.ts
> Fix(@inquirer/core): Add SIGINT handler to make sure the prompt throw an exit error.

- packages/checkbox/checkbox.test.ts
- packages/checkbox/src/index.ts
- packages/select/src/index.ts
- packages/select/test/select.test.ts
Fixes #1786
Fix implemented in both checkbox and select prompts.
> Ignore separators when selecting item with a number key
